DROP TABLE IF EXISTS CONTENT;
CREATE TABLE CONTENT (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
title VARCHAR(100) NOT NULL,
description VARCHAR(256) NOT NULL,
type VARCHAR(50) NOT NULL,
mimetype INT,
url VARCHAR(256),
parentId INT
);